### ISSUE TITLE
[BUG] CONNECTION_TIMED_OUT on build

### ISSUE THREAD

**Issue by fpasalioglu** [OpenIMSDK/Open-IM-SDK-Flutter#100]
**Describe the bug**
Timeout on library url :

http://121.37.25.71:8081/repository/maven2/io/openim/core-sdk/2.3.4-rc0/core-sdk-2.3.4-rc0.pom
ERR_CONNECTION_TIMED_OUT

**How to reproduce**
Just build fresh project

**Comment by hrxiang** [comment]
https://open-im-online.rentsoft.cn:51000/repository/maven2/  使用这个仓库地址

**Comment by fpasalioglu** [comment]
https://github.com/OpenIMSDK/Open-IM-SDK-Flutter/blob/main/android/build.gradle 这里的地址需要更改。
我改变它。
