### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by 9527001** [OpenIMSDK/Open-IM-SDK-Flutter#103]
**Describe the bug**

 

1. 从相册中获取路径图片路径【 /data/user/0/com.im30.mind/app_flutter/pic/work_moment_1668671386430.webp】
2. createImageMessageFromFullPath 返回结果是空
3. jpg格式正常获取正确是的实体

 

![image](https://user-images.githubusercontent.com/16686832/202435427-e2fc4dcf-4bc5-4d17-ab34-44787bc32d6a.png)

**Version information**
- Device: huawei*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v2.3.3.6)
- Flutter Version: *e.g. v3.3.2

**Comment by hrxiang** [comment]
文件格式 识别不出来
