### ISSUE TITLE
为什么隐藏了 flutter sdk 中 markSingleMessageHasRead

### ISSUE THREAD

**Issue by dev-zl** [OpenIMSDK/Open-IM-SDK-Flutter#107]
![image](https://user-images.githubusercontent.com/36152331/224244894-d75ccb74-3dd2-4ab3-b2a4-c196c19851fb.png)
还有 关于获取会话总未读数 是否可以区分类型进行获取
OpenIM.iMManager.conversationManager.getTotalUnreadMsgCount()

**Comment by dev-zl** [comment]
> markSingleMessageHasRead很久以前就废除了。使用以下方法代替
> 
> ![200001678431876_ pic](https://user-images.githubusercontent.com/7018230/224248860-b038b985-31fe-4684-84e4-f26311aaf4c6.jpg)
> 
> getTotalUnreadMsgCount返回的是String类型，为了不影响已经使用sdk做开发的用户一直未调整。
> 
> 你可以转换：
> 
> ```
> final count = await getTotalUnreadMsgCount();
> int value = int.tryParse(count) ?? 0;
> ```

谢谢你的回答，但是 markMessageAsReadByConID 、markC2CMessageAsRead  必须要传递 消息clientMsgID集合，那么太部分场景是 让这个会话改成已读，而不是去操作会话中的消息一个一个设置已读，这很麻烦

可否重新开放 markSingleMessageHasRead 类似于这样的api 让整个会话设置为已读，而不是对于会话中的消息一个一个去设置

**Comment by hrxiang** [comment]
集合传空就是标记所有，可以阅读文档哈。

**Comment by dev-zl** [comment]
okok  感谢大佬
