### ISSUE TITLE
[BUG] 多次启动会导致消息发不出去

### ISSUE THREAD

**Issue by zhanglijie5997** [OpenIMSDK/Open-IM-SDK-Flutter#109]
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/42401363/233293620-3748b2a0-03dd-4d18-9e21-f5fb1fdf14bd.png">
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/42401363/233293728-8637389e-602f-4704-a519-c6defb8f95c6.png">
有时候需要重新退出登陆一下才可以发消息

**Comment by pppshiwen** [comment]
遇到同样的问题，请问怎么解决的
