### ISSUE TITLE
[BUG] jsondecode failed with empty message when send picture/video in ios device

### ISSUE THREAD

**Issue by osangma** [openimsdk/open-im-sdk-flutter#113]
OpenIM-App] ** --------assets type-----AssetType.image, isError [false]
2023-07-27 05:32:24.589	INFO	[PID:37214]	[open_im_sdk/util.go:245]	input req	{"operationID": "1690435944517", "function name": "open_im_sdk/internal/conversation_msg.(*Conversation).CreateImageMessageFromFullPath-fm", "args": ["/private/var/mobile/Containers/Data/Application/071B857A-5C07-4F21-BA25-DCE8B083FBC1/tmp/flutter-images/4d8004bfc31689632c45fff93b02393b_exif.jpg"]}
fnv: 0x1056b3b80 ins: [<*context.valueCtx Value> /private/var/mobile/Containers/Data/Application/071B857A-5C07-4F21-BA25-DCE8B083FBC1/tmp/flutter-images/4d8004bfc31689632c45fff93b02393b_exif.jpg]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      Utils.formatJson
utils.dart:12
#7      Utils.toObj
utils.dart:8

environment:
iphone 13 mini:

flutter_openim_sdk: 
    git:
      url: git@github.com:OpenIMSDK/Open-IM-SDK-Flutter.git
      ref: main
OpenimSdkCore 3.0.1

ios真机发送图片/视频消息时，sdkcore 返回的message为空，导致flutter无法jsondecode

**Comment by osangma** [comment]
any updates?

**Comment by std-s** [comment]
Refer to the open source demo.

**Comment by abel-wang-git** [comment]
Same question
Simulator can send Physical devices are not working

**Comment by std-s** [comment]
@abel-wang-git

**Comment by junixapp** [comment]
same issue

**Comment by junixapp** [comment]
> @abel-wang-git hi, `initSDK( "dataDir: path,"`) this input parameter needs to end with "/". like this: `"dataDir: xx/xx/" `

这个也太坑了，搞了我3天3夜才找到你这个issue
