### ISSUE TITLE
[BUG] Error with something

### ISSUE THREAD

**Issue by yuantianxiang** [openimsdk/open-im-sdk-flutter#114]
群组发送消息失败
[OpenIM-App] ** message send failed e :PlatformException(1001, 1001 ArgsError, null, null)  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)

**Comment by std-s** [comment]
@yuantianxiang Refer to the open source demo.
