### ISSUE TITLE
[BUG] maven仓库地址无法访问

### ISSUE THREAD

**Issue by cqzongjian** [openimsdk/open-im-sdk-flutter#117]
**Describe the bug**
https://open-im-online.rentsoft.cn:51000/repository/maven2/ 该地址无法访问

**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Additional context**

**Comment by std-s** [comment]
Hi, it has been started.
