### ISSUE TITLE
How to integrate my own Go-compiled OpenIMSDKCore into the iOS version?

### ISSUE THREAD

**Issue by mymirror** [openimsdk/open-im-sdk-flutter#119]
由于业务的需要，需要后台修改go源码来适应公司的业务需求，go编译后得到的openimsdkcore静态库，如何集成到flutter 插件里面

**Comment by std-s** [comment]
Hi, let’s first learn some knowledge about the flutter plug-in.

The replacement Core package is commented in the relevant places of the flutter plug-in.

**Comment by std-s** [comment]
No response for too long, close it temporarily.
