### ISSUE TITLE
[BUG] When the other party clears the read status, our side crashes and exits

### ISSUE THREAD

**Issue by jijkbird** [openimsdk/open-im-sdk-flutter#120]
E/Go      ( 9563): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 9563): [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb6ef7e22]
E/Go      ( 9563): 
E/Go      ( 9563): goroutine 71 [running]:
E/Go      ( 9563): github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).doReadDrawing(0x861ba8f0, {0xb725a880, 0x864b0b58}, 0x863102c0)
E/Go      ( 9563): 	github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/conversation_msg/read_drawing.go:229 +0x1332
E/GoLog   ( 9563): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 9563): github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).doNotificationNew(0x861ba8f0, {{0xb67689a5, 0x3}, {0xb71b43a0, 0x86502ef8}, {0xb725a880, 0x864b0b58}})
E/Go      ( 9563): 	github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/conversation_msg/conversation_notification.go:698 +0xf7d
E/Go      ( 9563): github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).Work(0x861ba8f0, {{0xb67689a5, 0x3}, {0xb71b43a0, 0x86502ef8}, {0xb725a880, 0x864b0b58}})
E/Go      ( 9563): 	github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/conversation_msg/conversation_notification.go:49 +0x2e6
E/Go      ( 9563): github.com/openimsdk/openim-sdk-core/v3/pkg/common.DoListener({0xb7259060, 0x861ba8f0}, {0xb725a820, 0x86259020})
E/Go      ( 9563): 	github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/common/trigger_channel.go:212 +0x4e
E/Go      ( 9563): created by github.com/openimsdk/openim-sdk-core/v3/internal/login.(*LoginMgr).login
E/Go      ( 9563): 	github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/internal/login/init_login.go:302 +0x15f1
F/libc    ( 9563): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9614 (Thread-8), pid 9563 (plus.lure.plus)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2023-10-03 21:19:41+0800
pid: 9563, tid: 9614, name: Thread-8  >>> plus.lure.plus <<<
uid: 10158
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

============================================================================================

A向B发送消息，B清除A的未读消息，A崩溃退出
OpenIM.iMManager.conversationManager
        .markConversationMessageAsRead(conversationID: id);

flutter_openim_sdk: ^3.3.0
[✓] Flutter (Channel stable, 3.13.4, on Ubuntu 22.04.3 LTS 6.2.0-33-generic, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by std-s** [comment]
Will this problem still occur after updating the SDK?
