### ISSUE TITLE
error *errors.withStack not implement CodeError: not load resource: 10004 ResourceLoadNotCompleteError

### ISSUE THREAD

**Issue by 402162095** [openimsdk/open-im-sdk-flutter#124]
error *errors.withStack not implement CodeError: not load resource: 10004 ResourceLoadNotCompleteError

**Comment by 402162095** [comment]
iphone6 ios12.5.7

**Comment by std-s** [comment]
@402162095 hi, 

login needs to be completed before calling other APIs.
