### ISSUE TITLE
When I create a group with open-im-sdk-flutter 3.5.0.rc1,it throws error "no such table: local_super_groups"

### ISSUE THREAD

**Issue by xiaobeiy** [openimsdk/open-im-sdk-flutter#131]
**Describe the bug**
When I create a group with open-im-sdk-flutter 3.5.0.rc1，it throws error "no such table: local_super_groups"。

I/GoLog   (13341): 2024-01-04 12:04:18.456      DEBUG   [PID:13341]     [log/sql_logger.go:86]  sql exec detail {"operationID": "1704369858122", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/group_model.go:56", "elapsed time": "5.444271(ms)", "rows": 94, "sql": "SELECT * FROM `local_groups`"}
I/GoLog   (13341): 2024-01-04 12:04:18.457      ERROR   [PID:13341]     [log/sql_logger.go:71]  sql exec detail {"operationID": "1704369858122", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/super_group_model.go:32", "elapsed time": "0.279167(ms)", "rows": 0, "sql": "SELECT * FROM `local_super_groups`", "error": "no such table: local_super_groups"}
I/GoLog   (13341): 2024-01-04 12:04:18.457      ERROR   [PID:13341]     [open_im_sdk/caller.go:109]     fn call error   {"operationID": "1704369858122", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/group.(*Group).CreateGroup-fm", "cost time": "332 ms", "error": "==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetJoinedSuperGroupList()@38: GetJoinedSuperGroupList failed : no such table: local_super_groups"}
I/F-OpenIMSDK(native call flutter)(13341): method: 【 createGroup 】, onError: { code:10005, message:error *errors.withStack not implement CodeError: ==> github.com/openimsdk/openim-sdk-core/v3/pkg/db.(*DataBase).GetJoinedSuperGroupList()@38: GetJoinedSuperGroupList failed : no such table: local_super_groups}
I/GoLog   (13341): 2024-01-04 12:04:18.568      INFO    [PID:13341]     [interaction/long_conn_mgr.go:439]      recv msg        {"operationID": "1704369858122", "errCode": 0, "errMsg": "", "reqIdentifier": 2001}

实际上，群组已经创建了，但调用OpenIM.iMManager.groupManager.createGroup时却没有返回群组GroupInfo信息，而是报了上面的错。
**How to reproduce**
创建一个群组即可复现该错误。

**Version information**
-open-im-sdk-flutter 3.5.0.rc1
- Flutter Version: 3.16.5

**Comment by xiaobeiy** [comment]
open-im-server 3.5.0版本

**Comment by FGadvancer** [comment]
Resolves https://github.com/openimsdk/openim-sdk-core/pull/479
