### ISSUE TITLE
[BUG] OpenIM Integration Issue in Existing Flutter App

### ISSUE THREAD

**Issue by akashshrestha123** [openimsdk/open-im-sdk-flutter#136]
I'm facing an issue where the OpenIM SDK works perfectly in a standalone Flutter app but fails to function correctly when integrated into my existing Flutter application. I've followed the integration instructions carefully, but I'm still unable to get OpenIM features working within my existing app.

Here's a summary of what I've tried:

- **Double-checked Initialization**: I've ensured that OpenIM is initialized only once in my app.
- **Verified Dependencies**: My existing app has all the required permissions, and I'm using compatible versions of the OpenIM SDK, Flutter, and other dependencies.
- **Checked Configuration**: I've verified that the server information (address, API key, etc.) is correct in the OpenIM configuration.
- **Ensured Network Connectivity**: My app has a stable internet connection.
- **Tested in Isolation**: I've created a minimal Flutter app that only integrates OpenIM, and it works as expected.

Could you please help me with the following questions:

**Are there any known compatibility issues between OpenIM and the specific versions of Flutter or other dependencies I'm using in my existing app?**
**Are there any specific configuration settings or steps that are critical for successful integration within an existing Flutter app?
Could there be any conflicts between the OpenIM SDK and other libraries or components in my existing app?**
**Are there any debugging techniques or tools you recommend to identify the root cause of this integration problem?**

Additional Tips:

- Got Listener logs at native side but couldn't get in flutter app. 
- Got only Initial logs at native side and flutter side.

**Comment by std-s** [comment]
@akashshrestha123 
Hi, please provide the error information.

**Comment by akashshrestha123** [comment]
Hey @std-s  thank you so much for your response. I don't any kinds of error logs. since i have few question . 
**Urgent: OpenIM Listener Callbacks Not Triggering in Embedded Flutter App**

We are encountering a critical issue with the OpenIM Flutter SDK not triggering listener callbacks when integrated into our existing Flutter application.

**Key Points:**

* **Environment:**
    - Flutter Version: 3.0.2
    - OpenIM Flutter SDK: 3.5.1
    - Additional relevant dependencies: Firebase, `go_router`, `provider`, etc. 
* **Successful Connection:** We can confirm from native logs that the `onConnectSuccess` event is successfully triggered on the native side (both Android and iOS). 
* **Listener Not Called:** However, the corresponding listener callbacks defined in our Flutter code are not being executed.
* **Standalone Works:** We have tested the OpenIM SDK in a minimal, standalone Flutter app, and the listener callbacks work as expected in that environment.

**Steps Taken:**

* Verified that method channel names match exactly between Flutter and native code.
* Ensured listener registration happens before or during `initSDK`.
* Made the listener a class member to avoid garbage collection.
* Used `scheduleTask` for Android to ensure callbacks on the main thread.
* Checked for conflicting plugins or dependencies by temporarily disabling them.
* Verified the correctness of `initSDK` parameters.

**Request to OpenIM Team:**

1. **Are there any known compatibility issues:**  Specifically between the OpenIM Flutter SDK v3.5.1 and our Flutter version (3.0.2) or other dependencies we are using?

2. **Specific Configuration for Embedded Apps:** Are there any special configuration settings or steps required when embedding the OpenIM SDK within an existing Flutter app (as opposed to a standalone app)?

3. **Possible Conflicts:** Could there be potential conflicts between the OpenIM SDK and other libraries or components commonly used in Flutter apps, such as Firebase or `go_router`?

4. **Debugging Recommendations:** Could you provide more guidance on how to further debug this issue? Are there specific logs or areas in the native code that we should focus on to identify the problem?

5. **Alternative Solutions:** Are there any alternative approaches or workarounds you recommend for handling listener callbacks when embedding the OpenIM SDK in a complex Flutter app?

**Additional Notes:**

* We are not seeing any error messages in the Flutter console or native logs related to the OpenIM SDK initialization or connection.
* We have also tried clearing the Flutter cache, rebuilding the project, and restarting the IDE, but the issue persists.

We would greatly appreciate any assistance you can provide in resolving this issue. Please let us know if you need any further information or code snippets to help you diagnose the problem.

**Comment by std-s** [comment]
@akashshrestha123 hi, Have you set up a listener? Something like [this](https://github.com/openimsdk/open-im-flutter-demo/blob/main/lib/core/controller/im_controller.dart).

**Comment by akashshrestha123** [comment]
@std-s Yeah exactly i did. when i create simple app doing this all it is working correctly calling every listener method in flutter side but when integrate in my existing e-learning app only "onConnecting" is called in flutter side after that nothing is called in flutter side but when i see logger that is came  from native side every listener method is calling properly.

**Comment by cipchk** [comment]
I have the exact same situation, but my iOS works fine. However, on Android, only onConnecting and onConnectSuccess are triggered, and none of the other event listeners are triggered at all.

We can obtain the following logs, but we are unable to trigger Flutter's listening events.

```
I/F-OpenIMSDK(flutter call native)(19498): { class:conversationManager,  method:setConversationEx }
I/F-OpenIMSDK(flutter call native)(19498): { class:conversationManager,  method:getConversationListSplit }
I/F-OpenIMSDK(flutter call native)(19498): { class:conversationManager,  method:setConversationEx }
```

Doctor -v:

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Users/cipchk/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cipchk/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/cipchk/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/cipchk/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • SM G996U (mobile) • RFCNC0J4X2J • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 126.0.6478.63
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Users/cipchk/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (4 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cipchk/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/cipchk/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/cipchk/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • SM G996U (mobile) • RFCNC0J4X2J • android-arm64  • Android 14 (API 34)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 126.0.6478.63
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by std-s** [comment]
@akashshrestha123  @cipchk  
Hi, the main steps are to initialize the SDK, set the listener, and log in. [This file](https://github.com/openimsdk/open-im-flutter-demo/blob/main/lib/core/controller/im_controller.dart) shows the functions of initializing the SDK and setting the listener. You can run our open source [Demo](https://github.com/openimsdk/open-im-flutter-demo) first.

**Comment by cipchk** [comment]
@std-s  My test phone is a Samsung. How about you? @akashshrestha123 

Other than **Samsung** (Galaxy S21+ 5G), I have tested brands like Xiaomi and Huawei, and everything works fine.

**Comment by akashshrestha123** [comment]
@cipchk mine also samsung galaxy a50. and are you sure it is working in xiaomi and huawei. are you creating simple or integrating in existing project?

**Comment by akashshrestha123** [comment]
@std-s is it something with flutter version also? since i am at flutter version 3.0.2. When i create simple app or creating new project every single listener and every thing is working correctly. Since i have a little heavy application that is e-learning and has a lot of package used. Did i miss something? Does it also depends on how our flutter project is structured?

**Comment by cipchk** [comment]
@akashshrestha123 Yes, my Samsung device is similar to yours. Since we need to launch on Google Play, the minimum build version required is 30 or above. However, the official version provided is 26, so I feel the issue might be with the build version. I don't have the means to test this on my end; could you possibly conduct some tests on the build level? I believe it is indeed a build issue.

**Comment by cipchk** [comment]
@akashshrestha123 Any progress?

**Comment by akashshrestha123** [comment]
@cipchk Thank you for you reply. I haven't tried yet. I will try and let you know.

**Comment by cipchk** [comment]
@akashshrestha123  Any progress?

**Comment by akashshrestha123** [comment]
@cipchk i tried but still same issue. Any progress from your side?

**Comment by cipchk** [comment]
I can work, but I can't explain to you why because I didn't make any fixes and it suddenly started working again without any warning.

The only thing I can think of that has changed is the User Token, you could try redeploying OPENIM Serve and see if that solves your problem.

It's a very strange phenomenon that I can't explain.

**Comment by akashshrestha123** [comment]
Yeah I do understand. I am also facing strange issue. when i create new project and try to run it is working properly but i am still facing same issue on integrating in existing system. At the moment i am feeling helpless and asking my team should we find other ways. Please give me any other solution if you have.

**Comment by std-s** [comment]
It hasn't made any sound for a long time, turn it off first.

**Comment by cipchk** [comment]
@akashshrestha123 当我在编写另一个 Flutter 插件时，我无意中在 `invokeMethod` 监听了调用结果时会抛出 `notImplemented` 时，我想是不是 open-im-sdk-flutter 也有类似情况 ，的确出乎我的意料，在三星设备中调整生命周期来改变 `MethodChannel` 实例的顺序时，这个 BUG 意外的解决了，我无法得知为什么会这样，但这的确解决了三星设备无法同步的问题。

你可以尝试一下这个版本：

```diff
- # flutter_openim_sdk: ^3.8.1
+ flutter_openim_sdk:
    git:
      url: https://github.com/cipchk/open-im-sdk-flutter.git
      ref: issues-galaxy
```

**Comment by Kimsoer** [comment]
I got the same this issue, for trying in demo project work while i embed to my existing project it have the same issue

**Comment by Kimsoer** [comment]
@cipchk Can you give me how to fixed this issue?

**Comment by cipchk** [comment]
@Kimsoer You can try:


```diff
- # flutter_openim_sdk: ^3.8.1
+ flutter_openim_sdk:
    git:
      url: https://github.com/cipchk/open-im-sdk-flutter.git
      ref: issues-galaxy
```

**Comment by wyz2001** [comment]
https://github.com/cipchk/open-im-sdk-flutter/commit/c1a019ee5b23c0950067a15dd26fba65e4a0fd4d。help me

**Comment by wyz2001** [comment]
https://github.com/cipchk/open-im-sdk-flutter/commit/c1a019ee5b23c0950067a15dd26fba65e4a0fd4d  对我有帮助

**Comment by yongjianyu** [comment]
@cipchk Can the latest version of flutter_openim_sdk solve this problem and support callbacks on Samsung phones?
