### ISSUE TITLE
[BUG] When you install it for the first time, all messages will be synchronized. When you have thousands of friends, it will be very laggy. Normally, you should only synchronize 50 messages. When it drops, synchronize more messages #1

### ISSUE THREAD

**Issue by junixapp** [openimsdk/open-im-sdk-flutter#139]
**Describe the bug**
首次安装会同步所有消息，上千个好友的时候会非常卡，正常应该只同步50条，下滑的时候去同步更多

**How to reproduce**
所有版本都存在的问题

好友比较多，并且消息比较多的时候。卸载重装就会复现

**Expected behavior**
正常应该只同步每个会话记录的最近50条，下滑的时候去同步更多历史消息

**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Comment by std-s** [comment]
@junixapp hi, please use flutter_openim_sdk: ^3.8.0.
