### ISSUE TITLE
[BUG] use onRecvOfflineNewMessage cant receive message

### ISSUE THREAD

**Issue by pokid** [openimsdk/open-im-sdk-flutter#141]
**Describe the bug**

**How to reproduce**

1. debug my app in my real phone
2. let my app run in background
3. use web ,send message to my app
4.no log and no notification

**Expected behavior**

**Version information**
- Device: *iPhone 12*
- OS: *iOS 14.7.1*
- Package Version: *3.8*
- Flutter Version: *v3.19.0*

**Comment by std-s** [comment]
hi，On iOS, you need to use the PUSH function.
