### ISSUE TITLE
After updating to 3.8.0, there were issues with the group related APIs

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#149]
![7021723515796_ pic](https://github.com/user-attachments/assets/a8de5230-c39f-41de-a3e9-17fb2f1172b8)
E/flutter (32587): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10005, error *errors.withStack not implement CodeError: 1004 RecordNotFoundError, null, null)

**Comment by std-s** [comment]
hi, the server needs to be updated to 3.8.

**Comment by std-s** [comment]
Close it first, and if the problem persists, reopen it.
