### ISSUE TITLE
[BUG] flutter_openim_sdk error Unhandled Exception: PlatformException(10303, 10303 unread count has zero, null, null) 

### ISSUE THREAD

**Issue by LionYan-Coder** [openimsdk/open-im-sdk-flutter#150]
**Describe the bug**

     Launching the app, going to chat and going back to conversation will result in this error and is only available on ios

    [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10303, 10303 unread count has zero, null, null)

**How to reproduce**

1. Go to Conversation page
2. Click  any chat
3.  back Conversation page
4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

<img width="814" alt="356962166-0e5c6ae1-3def-469c-b26d-e7feb703b0b6" src="https://github.com/user-attachments/assets/47cc9ad4-0dc3-4836-8d42-73c9cb1e4be2">

**Version information**
- Device: *e.g. iPhone 15*
- OS: *e.g. iOS 17.0.1*
- Package Version: *e.g. v3.8.0*
- Flutter Version: *e.g. v3.22.0*

**Additional context**

**Comment by std-s** [comment]
Hi, does this session have any unread counts? If there are no unread counts, there is no need to call this API.

**Comment by TheOneT1** [comment]
请问你如何解决的这个问题，我也遇到了这个问题 @LionYan-Coder @std-s

**Comment by std-s** [comment]
If the conversation's unread count is 0, there is no need to call 'markConversationMessageAsRead'.

**Comment by skiffer-git** [comment]
This shouldn't be considered an exception.
Is it better to handle this issue within Flutter, or should it be dealt with at the SDK core level?

@std-s

**Comment by std-s** [comment]
The sdk handles it better.
