### ISSUE TITLE
[Feature] Add namespace attribute to build.gradle

### ISSUE THREAD

**Issue by zengyun261** [openimsdk/open-im-sdk-flutter#151]

**Comment by std-s** [comment]
Hi, can you share the code?

**Comment by Aquarius-M** [comment]
> Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@191009e of type BuildFlowService.Parameters
> A problem occurred configuring project ':flutter_openim_sdk'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> Namespace not specified. Specify a namespace in the module's build file: xxx/hosted/pub.flutter-io.cn/flutter_openim_sdk-3.8.0/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by zengyun261** [comment]
> Hi, can you share the code?

The Android Gradle Plugin 8.x requires the namespace field to be present in the build.gradle file; otherwise, the compilation will fail.

**Comment by std-s** [comment]
There is currently no official plan to upgrade "Gradle".

**Comment by std-s** [comment]
Turn it off for now.
