### ISSUE TITLE
[BUG] PlatformException (PlatformException(10005, error *errors.withStack not implement CodeError: GetFriendList failed: disk I/O error: read-only file system, null, null))

### ISSUE THREAD

**Issue by fatesinger** [openimsdk/open-im-sdk-flutter#152]
**Describe the bug**

When there is too much conversation messages, calling conversationManager.getConversationListSplit will report an error.
![image](https://github.com/user-attachments/assets/2116eabc-d8d6-4e35-8967-d070a2fdc283)

**How to reproduce**

Use [open-im-flutter-demo](https://github.com/openimsdk/open-im-flutter-demo)

1. Create 1,000 group conversation messages.
2. After synchronization.
3. Kill the app process and re-enter.
4. Go to conversation.
5. Scroll to the bottom.
6. Scroll again.
8. When offset is 320.
9. Error occurred.

**Expected behavior**

Conversation messages are loaded correctly

**Screenshots (If contains)**

![image](https://github.com/user-attachments/assets/a655cf87-17b6-4fc0-b773-504fe02a5e54)

**Version information**
- Device: *OPPO REMO4 5G*
- OS: *Android 10*
- Package Version: *3.8.1+31*
- Flutter Version: *3.22.3*
- Flutter Openim Sdk Version: *^3.8.0* 

**Additional context**

**Comment by std-s** [comment]
Hi, set count to a smaller value. For example, 50, 100.

**Comment by fatesinger** [comment]
Now the count is 40. I changed the count to 20, but the problem still remains.

```dart
final pageSize = 20;

void onLoading() async {
  late List<ConversationInfo> list;
  try {
    list = await _request(this.list.length);
    this.list.addAll(list);
  } finally {
    if (list.isEmpty || list.length < pageSize) {
      refreshController.loadNoData();
    } else {
      refreshController.loadComplete();
    }
  }
}

_request(int offset) =>
    OpenIM.iMManager.conversationManager.getConversationListSplit(
      offset: offset,
      count: pageSize,
    );
```

**Comment by std-s** [comment]
The function reporting the error is "getFriendList".

**Comment by fatesinger** [comment]
Please try this code.

```dart

List list = [];
final pageSize = 50;

getConversationList(int offset) async {
  var list = await OpenIM.iMManager.conversationManager.getConversationListSplit(
    offset: offset,
    count: pageSize,
  );
  return list;
}
  
FloatingActionButton(
  onPressed: () async {
    var result = await getConversationList(400);
    setState(() {
      list = result;
    });
  },
)
```

![image](https://github.com/user-attachments/assets/8db5d456-ce5b-4dc9-9d68-d2bb167386d2)

**Comment by std-s** [comment]
The exception information shows that something went wrong with "GetFriendList".
