### ISSUE TITLE
Support modifying the 'filepath' in 'FileElem'

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#153]
The "FileElem "of "filePath" in the file message is the local resource path of the sender. How can I change this path in the program. My business scenario is that after the receiver receives the sender's file, I want the receiver's "filePath" to be their own file path instead of the sender's file path

**Comment by std-s** [comment]
Hi, message editing is not currently supported.

**Comment by hujian-jian** [comment]
> 您好，目前不支持消息编辑。

Can only be operated through setmessageLocalEx at present

**Comment by hujian-jian** [comment]
> 您好，目前不支持消息编辑。
Can only be operated through setmessageLocalEx at present？

**Comment by std-s** [comment]
#154
