### ISSUE TITLE
The setmessageLocalEx api is invalid

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#154]
![6381724661311_ pic](https://github.com/user-attachments/assets/7b05c58c-8cd8-4fe8-a7df-d70191345467)

![6391724661466_ pic](https://github.com/user-attachments/assets/6a84f040-ee78-47c6-bf4e-cb8ce5028ff4)

**Comment by std-s** [comment]
You can pay attention to the "localEx" field.

**Comment by hujian-jian** [comment]
Thanks
