### ISSUE TITLE
[Feature] TokenNotExistError listener

### ISSUE THREAD

**Issue by LionYan-Coder** [openimsdk/open-im-sdk-flutter#156]
**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Is your feature request related to a problem?**

**Describe the solution you'd like**

希望可以加个客户端不存在或者错误的 OnConnectListener ，我好像在哪个版本看到了有这个？但是现在3.8.0 没有，我认为挺重要的这个

**Describe alternatives you've considered**

**Additional context**

**Comment by std-s** [comment]
hi, you can pay attention to these two [monitors](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/listener/connect_listener.dart#L7).

**Comment by LionYan-Coder** [comment]
> hi, you can pay attention to these two [monitors](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/listener/connect_listener.dart#L7).

Thanks

**Comment by std-s** [comment]
Close it first, then open it again if there is a problem.
