### ISSUE TITLE
Unable to receive type message being entered by the other user in ‘onRecvNewMessage’

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#157]
![7531725265667_ pic](https://github.com/user-attachments/assets/cb6b12ec-7d23-4288-bebe-81313e3235fa)

My open-im-sdk-flutter version：^3.8.1-rc.0

**Comment by std-s** [comment]
hi, The API has been changed, please refer to [here](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/manager/im_conversation_manager.dart#L393) and the corresponding [listener](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/listener/conversation_listener.dart#L13).

**Comment by hujian-jian** [comment]
> hi, The API has been changed, please refer to [here](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/manager/im_conversation_manager.dart#L393) and the corresponding [listener](https://github.com/openimsdk/open-im-sdk-flutter/blob/9f57971ee9842169816d6a883c490390b29f75af/lib/src/listener/conversation_listener.dart#L13).

ok,thanks
