### ISSUE TITLE
I am listening to onInputStatusChanged in chatLogic, and I am listening to the user's soft keyboard and using OpenIM.iMManager. conversionManager. changeInputStates( ), but onInputStatus Changed is not responding

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#158]
![6441725270708_ pic](https://github.com/user-attachments/assets/719d397d-632f-47cc-94ed-e3d721b85e0a)
![Uploading 6461725270760_.pic.jpg…]()
![6471725270780_ pic](https://github.com/user-attachments/assets/fda466e5-1be9-48cd-b019-f2791efc4885)

**Comment by hujian-jian** [comment]
![6481725270848_ pic](https://github.com/user-attachments/assets/e9884218-af97-473f-aaf1-7d425d448a7f)

**Comment by std-s** [comment]
There is a picture missing

**Comment by hujian-jian** [comment]
> 缺少一张图片
![WeChat4956d81f5a3d2021ef60d11fb0767d15](https://github.com/user-attachments/assets/3c911cb5-eb6a-48f4-a0f6-e668b8f94a97)

OnInputStatus Changed has no response

**Comment by std-s** [comment]
Please update the sdk.
