### ISSUE TITLE
Is there a specific platform description for ‘platformIDs’ in ‘UserStatusInfo’

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#159]
![6491725325243_ pic](https://github.com/user-attachments/assets/e2ca119c-1604-4731-a7d1-c6ef8f0310ef)
![6501725325352_ pic](https://github.com/user-attachments/assets/59fb54fd-90c0-4ecd-b931-bc04ac20f3bb)

**Comment by std-s** [comment]
https://docs.openim.io/sdks/enum/platform

**Comment by hujian-jian** [comment]
Ok，thanks
