### ISSUE TITLE
[BUG] setUploadFileListener does not work

### ISSUE THREAD

**Issue by LionYan-Coder** [openimsdk/open-im-sdk-flutter#161]
**Describe the bug**

    我在使用 OpenIM.iMManager.uploadFile 时候，需要监听当前文件上传进度，结果发现 setUploadFileListener 接受的 
   OnUploadFileListener 对象类没有提供构造函数，这是为什么？是要通过其他方式吗

**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

<img width="740" alt="截屏2024-09-28 17 40 24" src="https://github.com/user-attachments/assets/3dd44f73-fddf-42cf-8a4a-8379c02c1838">

**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Additional context**

**Comment by std-s** [comment]
@LionYan-Coder Hi, thanks for your question, we will update you soon.

**Comment by std-s** [comment]
Please update the sdk.
