### ISSUE TITLE
flutter_openim-sdk 3.8.1 does not expose SetGroupMembership Info to the public

### ISSUE THREAD

**Issue by hujian-jian** [openimsdk/open-im-sdk-flutter#166]
Cannot construct SetGroupMembershipInfo when changing member information
![771728456140_ pic](https://github.com/user-attachments/assets/9a6a195c-655a-4c44-b6a0-61b3345511be)
![791728456164_ pic](https://github.com/user-attachments/assets/8997c32a-6fa1-4ed3-8db1-c184c47396b5)

**Comment by std-s** [comment]
@hujian-jian #163
