### ISSUE TITLE
setConversation method params ConversationReq not public

### ISSUE THREAD

**Issue by whevether** [openimsdk/open-im-sdk-flutter#167]
**Describe the bug**
sdk @Deprecated('use [setConversation] instead')， But the model ConversationReq is not publicly available

**How to reproduce**
![image](https://github.com/user-attachments/assets/385dc7e3-a12d-466e-a66a-c60f444c4212)
ConversationReq is an internal class

**Expected behavior**
If certain methods are enabled. Please disclose the required model or class for the parameters

**Version information**
- Device: *e.g. iPhone 11*
- OS: *e.g. iOS 18.0.1*
- Package Version: *e.g. 3.8.1*
- Flutter Version: *e.g. v3.24.0*

**Additional context**

**Comment by std-s** [comment]
@whevether #163
