### ISSUE TITLE
[BUG] Error with run android

### ISSUE THREAD

**Issue by buiphukhuyen** [openimsdk/open-im-sdk-flutter#172]
![image](https://github.com/user-attachments/assets/e36a98de-9aa7-4a14-9a99-f28d03f6070c)

**Comment by JauneQ** [comment]
Check your network and remove it by yourself in [here](https://github.com/openimsdk/open-im-sdk-flutter/blob/main/android/build.gradle). We had been moved most release libraries to Maven Central. So it's useless now.
