### ISSUE TITLE
[BUG]  你们的地址访问不了https://open-im-online.rentsoft.cn:51000

### ISSUE THREAD

**Issue by sid-do-a-great-job** [openimsdk/open-im-sdk-flutter#173]
**Describe the bug**

![微信截图_20241111105344](https://github.com/user-attachments/assets/bfc6c484-a050-4692-803e-83033c84eff8)

**How to reproduce**

flutter build apk

flutter build apk

**Expected behavior**

打包成功

**Screenshots (If contains)**

**Version information**

```
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [版本 10.0.22631.4317], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.95.2)
[√] Connected device (3 available)
```

**Additional context**

**Comment by JauneQ** [comment]
Check your network and remove it by yourself in [here](https://github.com/openimsdk/open-im-sdk-flutter/blob/main/android/build.gradle). We had moved most release libraries to Maven Central. So it's useless now.

**Comment by std-s** [comment]
#172
