### ISSUE TITLE
[BUG] onRecvNewMessage function not working on android devices while ios devices still works fine

### ISSUE THREAD

**Issue by TheAnh188** [openimsdk/open-im-sdk-flutter#175]
@override
  void onInit() {
    super.onInit();
    _setMessageListener();
  }
void _setMessageListener() {
    openim.OnAdvancedMsgListener advancedMsgListener =
        openim.OnAdvancedMsgListener(
      onRecvNewMessage: (message) async {
        print('Da nhan tin nhan : 1 ' + message.textElem!.content!);
        _handleIncomingMessage(message);
      },
      onRecvOfflineNewMessage: (message) async {
        print('Da nhan tin nhan : 2 ' + message.textElem!.content!);
        _handleIncomingMessage(message);
      },
      onRecvOnlineOnlyMessage: (message) async {
        print('Da nhan tin nhan : 3 ' + message.textElem!.content!);
        _handleIncomingMessage(message);
      },
      onMsgDeleted: (message) {
        print('Da nhan tin nhan : 4 ' + message.textElem!.content!);
        messages.removeWhere(
            (chatMessage) => chatMessage.getId == message.clientMsgID);
      },
      onNewRecvMessageRevoked: (info) {
        print('Da nhan tin nhan : 5 ' + info.revokeTime.toString());
        messages.removeWhere(
            (chatMessage) => chatMessage.getId == info.clientMsgID);
      },
      //Xử lý trường hợp đối phương đã đọc tin nhắn
      onRecvC2CReadReceipt: (list) {
        print('Da nhan tin nhan : 6 ' + list.first.userID!);
        _handleReadReceipts(list);
      },
    );
    openim.OpenIM.iMManager.messageManager
        .setAdvancedMsgListener(advancedMsgListener);
  }
![Screenshot 2024-11-20 205806](https://github.com/user-attachments/assets/c2078549-5854-4ca8-9a1a-115c6c16a956)

**Comment by TheAnh188** [comment]
flutter_openim_sdk 3.8.1+2

**Comment by std-s** [comment]
hi, You can refer to the [Demo](https://github.com/OpenIMSDK/Open-IM-Flutter-Demo) now.
