### ISSUE TITLE
[BUG] Run Error with 3.8.2 for both Android & iOS

### ISSUE THREAD

**Issue by buiphukhuyen** [openimsdk/open-im-sdk-flutter#176]
<img width="778" alt="Screenshot 2024-11-24 at 09 31 15" src="https://github.com/user-attachments/assets/f794ac52-6de7-495f-941e-eb91e478251e">

<img width="945" alt="Screenshot 2024-11-24 at 09 32 00" src="https://github.com/user-attachments/assets/6978baf7-168a-430a-b9ec-ff3a21f890d5">

**Comment by std-s** [comment]
@buiphukhuyen  occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action

**Comment by std-s** [comment]
@buiphukhuyen iOS needs to update the pods repository. Then re-obtain 3.8.2 in the flutter project.
