### ISSUE TITLE
[BUG] Can not run my project when I updated flutter_openim_sdk 3.8.2

### ISSUE THREAD

**Issue by TheAnh188** [openimsdk/open-im-sdk-flutter#177]
### OpenIM SDK Version

3.8.2

### OpenIM Server Version

3.8.2

### SDK Platform

Flutter SDK

### Device Model

Pixel 2

### Operating System Version

.

### Bug Description and Steps to Reproduce

I couldn't run my project when I updated flutter_openim_sdk 3.8.2

### Screenshots Link

![image](https://github.com/user-attachments/assets/9d3d5213-cccc-442b-9eda-3dedde10183e)

**Comment by std-s** [comment]
#176
