### ISSUE TITLE
[BUG] There is no problem with the network. When getting chat records and sending messages, the speed is very slow. There is no other openIm interface.

### ISSUE THREAD

**Issue by BeiJiu123** [openimsdk/open-im-sdk-flutter#180]
网络没有任何问题,获取聊天记录和发送信息时,速度很慢 其他openIm的接口都没有问题
使用  AdvancedMessage am = await OpenIM.iMManager.messageManager
        .getAdvancedHistoryMessageList(
            conversationID: widget.sessionModel.conversationID, count: 20); 获取聊天记录很慢,大概七八秒的样子,
    Message msg = await OpenIM.iMManager.messageManager.sendMessage(
      message: message,
      groupID: widget.sessionModel.sessionType == 3
          ? widget.sessionModel.sourceID
          : null,
      userID: widget.sessionModel.sessionType == 1
          ? widget.sessionModel.sourceID
          : null,
      offlinePushInfo: OfflinePushInfo(
          title: "你有一条新消息！",
          desc: "",
          ex: "",
          iOSPushSound: "+1",
          iOSBadgeCount: true),
    );发送消息也特别慢,我的其他接口速度都是没问题的,就这两个特别慢

**Comment by std-s** [comment]
Hi, can you provide the logs of all messages sent by the client?

**Comment by BeiJiu123** [comment]
> Hi, can you provide the logs of all messages sent by the client?Hi, can you provide the logs of all messages sent by the client?您好，您能提供客户端发送的所有消息的日志吗？

没有任何日志,就是当发送的时候需要很久才能发送出去,第一次最慢,多发送几次就会正常起来,同时监听其他账号的发送信息的时候也是这样,一开始需要好几秒才能收到,然后慢慢的就是瞬间接收到

**Comment by std-s** [comment]
First, send out the complete log of the chat history.
