### ISSUE TITLE
[BUG] Due to confusion, Android cannot log in after packaging

### ISSUE THREAD

**Issue by BeiJiu123** [openimsdk/open-im-sdk-flutter#183]
我是用mac开发用的苹果模拟器功能一切正常,但是当我打包成apk以后,在登录的时候就无法登录进去,去掉openIm的登录以后才可以进去,android用数据线真机调试也是可以的,苹果打包上架商店也是可以的,唯独android打包apk以后就不可以了

**Comment by ZengSQI** [comment]
@BeiJiu123 
今天也遇到一樣的問題

可以試著加入
https://github.com/openimsdk/open-im-flutter-demo/blob/520cb146fde5e5705cb4a418ddf718d27a92ce49/android/app/build.gradle#L102
及
https://github.com/openimsdk/open-im-flutter-demo/blob/520cb146fde5e5705cb4a418ddf718d27a92ce49/android/app/proguard-rules.pro

避免 release 打包後 openim sdk 混淆

**Comment by BeiJiu123** [comment]
OK,确实可以了,感谢大佬

**Comment by std-s** [comment]
Now that it's solved, just close it.
