### ISSUE TITLE
[BUG] Could not find io.openim:core-sdk:2.3.5-t19

### ISSUE THREAD

**Issue by pppshiwen** [openimsdk/open-im-sdk-flutter#190]
**Describe the bug**

1.运行时flutter_openim_sdk 2.3.5报错
![image](https://github.com/user-attachments/assets/b68aff79-2ac8-48a5-a60e-7a85576a6625)

2.将flutter_openim_sdk的build.gradle修改
![image](https://github.com/user-attachments/assets/fb1d3ca6-7e5f-48e8-8342-dda792686d59)
3.还是出现报错
![image](https://github.com/user-attachments/assets/e987373a-83dc-418d-b8c8-060df29d37b2)
![image](https://github.com/user-attachments/assets/ce1f5e89-598a-4374-8af7-fda18c735a68)

**How to reproduce**

4. Error occurred.

**Expected behavior**

项目当前flutter_openim_sdk版本根据目前人手不想升级，只需要把当前项目运行起来，求帮助，麻烦了
**Screenshots (If contains)**

**Version information**
- Device: *e.g. Android *
- Package Version: *e.g. v2.3.5*
- Flutter Version: *e.g. v3.7.3*

**Additional context**

**Comment by pppshiwen** [comment]
@std-s @hrxiang @JauneQ

**Comment by JauneQ** [comment]
The SDK‘s version is too old, try to upgrade it nearby. The version information is [here](https://central.sonatype.com/search?q=io.openim&namespace=io.openim).

**Comment by JauneQ** [comment]
For this issue, it is recommended to upgrade to 2.3.5.

**Comment by pppshiwen** [comment]
> The SDK‘s version is too old, try to upgrade it nearby. The version information is [here](https://central.sonatype.com/search?q=io.openim&namespace=io.openim).
谢谢大佬的回复，我们项目目前人手不够，还来不及升级，只想运行起来，我看了依赖flutter
dependencies {
    api 'io.openim:core-sdk:2.3.5-t19@aar'
}
https://central.sonatype.com/artifact/io.openim/core-sdk/versions里面只有2.3.5，没有2.3.5-t19

**Comment by JauneQ** [comment]
We did not retain the old non-release SDK when migrating the library, so this issue cannot be resolved if you don't wanna to upgrade.

**Comment by JauneQ** [comment]
If there is really no other way, you can also get the file through the gradle cache and introduce it through local dependencies.

**Comment by pppshiwen** [comment]
目前我降级到2.3.5可以运行了，谢谢大佬 @JauneQ
