### ISSUE TITLE
flutter sdk支持web端吗？

### ISSUE THREAD

**Issue by tbc295** [OpenIMSDK/Open-IM-SDK-Flutter#33]

**Comment by hrxiang** [comment]
目前不支持，会给桌面端专门出一套sdk。后期也有计划flutter sdk 会全用dart开发，这样就能兼容各端。

**Comment by tbc295** [comment]
加油吧，年轻人，支持你们

**Comment by wtus** [comment]
> 目前不支持，会给桌面端专门出一套sdk。后期也有计划flutter sdk 会全用dart开发，这样就能兼容各端。

强烈建议出一个 dart 版本
