### ISSUE TITLE
no work to IOS simulator

### ISSUE THREAD

**Issue by IDONTSUDO** [OpenIMSDK/Open-IM-SDK-Flutter#39]
Launching lib/main_dev.dart on iPhone 12 in debug mode...
lib/main_dev.dart:1
Xcode build done.                                            1,3s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[99216]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f3f09160) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x114b142b8). One of the two will be used. Which one is undefined.
    objc[99216]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f3f091b0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x114b14308). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    ld: in /Users/idontsudo/.pub-cache/hosted/pub.dartlang.org/flutter_openim_sdk-0.0.9+1/ios/Framework/OpenIMCore.framework/OpenIMCore(000005.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/idontsudo/flutter-im-project/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Toast' from project 'Pods')

**Comment by myredsocks** [comment]
> Please use the latest version

thx, but now not build to release mode

**Comment by hrxiang** [comment]
Please update the sdk to : 1.0.2

**Comment by hrxiang** [comment]
> > Please use the latest version
> 
> thx, but now not build to release mode

Please update the sdk to : 1.0.2

**Comment by hrxiang** [comment]
```
flutter_openim_sdk:
       git:
          url: https://github.com/OpenIMSDK/Open-IM-SDK-Flutter.git
          ref: fix-ios-simulator
```

**Comment by lucasjinreal** [comment]
Hello, still not work, what I miss?

  flutter_openim_sdk: 3.4.0+2

Parse Issue (Xcode): Module 'flutter_openim_sdk' not found
