### ISSUE TITLE
'fluent build IOS' failed,'flutter build ios-framework' failed

### ISSUE THREAD

**Issue by chris99889** [OpenIMSDK/Open-IM-SDK-Flutter#43]
```
[   +3 ms] Encountered error while building for device.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand
(package:flutter_tools/src/commands/build_ios.dart:277:7)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

'fluent build IOS' failed  

```
[+1712 ms]  ├─Building plugins... (completed in 81.9s)
[   +1 ms] "flutter ios-framework" took 96,619ms.
[   +5 ms] Unable to build plugin frameworks for simulator: ** BUILD FAILED **
           
           
           The following build commands failed:
           	Ld

/Users/minia/Flutter-IM/Debug/iphonesimulator/Debug-iphonesimulator/flutter_openim_sdk/flutter_openim_sd
           	k.framework/flutter_openim_sdk normal
           (1 failure)
           
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      BuildIOSFrameworkCommand._producePlugins
           (package:flutter_tools/src/commands/build_ios_framework.dart:473:9)
           <asynchronous suspension>
           #2      BuildIOSFrameworkCommand.runCommand
           (package:flutter_tools/src/commands/build_ios_framework.dart:209:9)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```
'flutter build ios-framework' failed

Hello, is there a solution to this problem?thanks!

**Comment by hrxiang** [comment]
> ```
> [   +3 ms] Encountered error while building for device.
> [   +1 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      _BuildIOSSubCommand.runCommand
> (package:flutter_tools/src/commands/build_ios.dart:277:7)
>            <asynchronous suspension>
>            #2      FlutterCommand.run.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
>            <asynchronous suspension>
>            #3      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>            <asynchronous suspension>
>            #5      FlutterCommandRunner.runCommand.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
>            <asynchronous suspension>
>            #6      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
>            <asynchronous suspension>
>            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
>            <asynchronous suspension>
>            #9      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #10     main (package:flutter_tools/executable.dart:92:3)
>            <asynchronous suspension>
>            
>            
> [ +254 ms] ensureAnalyticsSent: 252ms
> [   +1 ms] Running shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 1
> ```
> 
> 'fluent build IOS' failed
> 
> ```
> [+1712 ms]  ├─Building plugins... (completed in 81.9s)
> [   +1 ms] "flutter ios-framework" took 96,619ms.
> [   +5 ms] Unable to build plugin frameworks for simulator: ** BUILD FAILED **
>            
>            
>            The following build commands failed:
>            	Ld
> 
> /Users/minia/Flutter-IM/Debug/iphonesimulator/Debug-iphonesimulator/flutter_openim_sdk/flutter_openim_sd
>            	k.framework/flutter_openim_sdk normal
>            (1 failure)
>            
> [   +1 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      BuildIOSFrameworkCommand._producePlugins
>            (package:flutter_tools/src/commands/build_ios_framework.dart:473:9)
>            <asynchronous suspension>
>            #2      BuildIOSFrameworkCommand.runCommand
>            (package:flutter_tools/src/commands/build_ios_framework.dart:209:9)
>            <asynchronous suspension>
>            #3      FlutterCommand.run.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
>            <asynchronous suspension>
>            #4      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
>            <asynchronous suspension>
>            #6      FlutterCommandRunner.runCommand.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
>            <asynchronous suspension>
>            #7      AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #8      FlutterCommandRunner.runCommand
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
>            <asynchronous suspension>
>            #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
>            <asynchronous suspension>
>            #10     AppContext.run.<anonymous closure>
> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #11     main (package:flutter_tools/executable.dart:92:3)
>            <asynchronous suspension>
>            
>            
> [ +254 ms] ensureAnalyticsSent: 252ms
> [        ] Running shutdown hooks
> [        ] Shutdown hooks complete
> [        ] exiting with code 1
> ```
> 
> 'flutter build ios-framework' failed
> 
> Hello, is there a solution to this problem?thanks!
