### ISSUE TITLE
IOS Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by mrtian** [OpenIMSDK/Open-IM-SDK-Flutter#44]
ld: warning: ignoring file /Users/TWY/servers/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-0.0.9+6/ios/Framework/OpenIMCore.framework/OpenIMCore, missing required architecture x86_64 in file /Users/TWY/servers/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-0.0.9+6/ios/Framework/OpenIMCore.framework/OpenIMCore (1 slices)
Undefined symbols for architecture x86_64:
  "_Open_im_sdkForceSyncMsg", referenced from:
      flutter_openim_sdk.MessageManager.forceSyncMsg(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateCardMessage", referenced from:
      flutter_openim_sdk.MessageManager.createCardMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateCustomMessage", referenced from:
      flutter_openim_sdk.MessageManager.createCustomMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateLocationMessage", referenced from:
      flutter_openim_sdk.MessageManager.createLocationMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateMergerMessage", referenced from:
      flutter_openim_sdk.MessageManager.createMergerMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateFileMessageFromFullPath", referenced from:
      flutter_openim_sdk.MessageManager.createFileMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateVideoMessageFromFullPath", referenced from:
      flutter_openim_sdk.MessageManager.createVideoMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateVideoMessage", referenced from:
      flutter_openim_sdk.MessageManager.createVideoMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateImageMessageFromFullPath", referenced from:
      flutter_openim_sdk.MessageManager.createImageMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateSoundMessageFromFullPath", referenced from:
      flutter_openim_sdk.MessageManager.createSoundMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateImageMessage", referenced from:
      flutter_openim_sdk.MessageManager.createImageMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkCreateTextAtMessage", referenced from:
      flutter_openim_sdk.MessageManager.createTextAtMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
  "_Open_im_sdkMarkC2CMessageAsRead", referenced from:

**Comment by hrxiang** [comment]
先用真机吧

**Comment by hrxiang** [comment]
> ld: warning: ignoring file /Users/TWY/servers/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-0.0.9+6/ios/Framework/OpenIMCore.framework/OpenIMCore, missing required architecture x86_64 in file /Users/TWY/servers/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-0.0.9+6/ios/Framework/OpenIMCore.framework/OpenIMCore (1 slices) Undefined symbols for architecture x86_64: "_Open_im_sdkForceSyncMsg", referenced from: flutter_openim_sdk.MessageManager.forceSyncMsg(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateCardMessage", referenced from: flutter_openim_sdk.MessageManager.createCardMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateCustomMessage", referenced from: flutter_openim_sdk.MessageManager.createCustomMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateLocationMessage", referenced from: flutter_openim_sdk.MessageManager.createLocationMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateMergerMessage", referenced from: flutter_openim_sdk.MessageManager.createMergerMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateFileMessageFromFullPath", referenced from: flutter_openim_sdk.MessageManager.createFileMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateVideoMessageFromFullPath", referenced from: flutter_openim_sdk.MessageManager.createVideoMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateVideoMessage", referenced from: flutter_openim_sdk.MessageManager.createVideoMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateImageMessageFromFullPath", referenced from: flutter_openim_sdk.MessageManager.createImageMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateSoundMessageFromFullPath", referenced from: flutter_openim_sdk.MessageManager.createSoundMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateImageMessage", referenced from: flutter_openim_sdk.MessageManager.createImageMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkCreateTextAtMessage", referenced from: flutter_openim_sdk.MessageManager.createTextAtMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o "_Open_im_sdkMarkC2CMessageAsRead", referenced from:

先用真机

**Comment by hrxiang** [comment]
![WeChat8b435b1abe8f0200616b6706bc55ef8b](https://user-images.githubusercontent.com/7018230/140445394-b8c7647e-f0bc-47af-b137-5718ace84c00.png)

**Comment by hrxiang** [comment]
Please update the sdk to : 1.0.2
