### ISSUE TITLE
maybe fixed or adding log mode???

### ISSUE THREAD

**Issue by IDONTSUDO** [OpenIMSDK/Open-IM-SDK-Flutter#46]
![image](https://user-images.githubusercontent.com/44754773/141116075-f4d8f423-ac20-448e-b3ed-986dbfe6d17d.png)

**Comment by hrxiang** [comment]
Does this mean?
`OpenIM.iMManager.setSdkLog(enable: false);`

**Comment by IDONTSUDO** [comment]
thx
