### ISSUE TITLE
getAllConversationList method dont work

### ISSUE THREAD

**Issue by IDONTSUDO** [OpenIMSDK/Open-IM-SDK-Flutter#48]
# problem 
 getAllConversationList return exception 

# dependeses: 
flutter_openim_sdk: 1.0.3
# log:
Launching lib/main_dev.dart on sdk gphone x86 arm in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 7937): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Connecting to VM Service at ws://127.0.0.1:43879/ih3z86zBEcs=/ws
I/F-OpenIMSDK(flutter call native)( 7937): { class:imManager,  method:initSDK }
I/GoLog   ( 7937): [ open_im_sdk_interface.go : 35 ] [InitSDK, config  {"dbDir":"\/data\/user\/0\/com.firephoenix.im.debug\/app_flutter\/","ipWs":"ws:\/\/132.226.232.50:30000","ManagerName":"imManager","ipApi":"http:\/\/132.226.232.50:10000","platform":2}]
I/GoLog   ( 7937): [ open_im_sdk_init_login.go : 16 ] [InitOnce success,  {2 http://132.226.232.50:10000 ws://132.226.232.50:30000 /data/user/0/com.firephoenix.im.debug/app_flutter/}]
I/GoLog   ( 7937): [ init_login.go : 29 ] [init success,  {"dbDir":"\/data\/user\/0\/com.firephoenix.im.debug\/app_flutter\/","ipWs":"ws:\/\/132.226.232.50:30000","ManagerName":"imManager","ipApi":"http:\/\/132.226.232.50:10000","platform":2}]
I/F-OpenIMSDK(flutter call native)( 7937): { class:conversationManager,  method:setConversationListener }
I/F-OpenIMSDK(flutter call native)( 7937): { class:friendshipManager,  method:setFriendListener }
I/GoLog   ( 7937): [ cmd_interface.go : 87 ] [doListener start. 0x78e284c0]
I/GoLog   ( 7937): [ cmd_interface.go : 89 ] [doListener for.]
I/flutter ( 7937): [2021-11-14 14:19:29.313317 | Catcher | WARNING] Screenshots path is empty. Screenshots won't work.
I/flutter ( 7937): [2021-11-14 14:19:29.340337 | Catcher | FINE] Catcher configured successfully.
I/F-OpenIMSDK(flutter call native)( 7937): { class:conversationManager,  method:getAllConversationList }
E/Go      ( 7937): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 7937): [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa93c7d1a]
E/Go      ( 7937):
E/Go      ( 7937): goroutine 24 [running]:
E/Go      ( 7937): sync.(*RWMutex).RLock(0x0)
E/Go      ( 7937): 	D:/Go/src/sync/rwmutex.go:48 +0x1a
E/Go      ( 7937): open_im_sdk.(*UserRelated).getAllConversationListModel(0xa9f4dc60, 0x0, 0x0, 0x0, 0x0, 0x0)
E/Go      ( 7937): 	C:/Users/Admin/go/src/open_im_sdk/data_model.go:438 +0x6d
E/Go      ( 7937): open_im_sdk.(*UserRelated).GetAllConversationList.func1(0xa9f4dc60, 0xa9be6c80, 0x78cacd5c)
E/Go      ( 7937): 	C:/Users/Admin/go/src/open_im_sdk/open_im_sdk_conversation_msg.go:18 +0x26
E/Go      ( 7937): created by open_im_sdk.(*UserRelated).GetAllConversationList
E/Go      ( 7937): 	C:/Users/Admin/go/src/open_im_sdk/open_im_sdk_conversation_msg.go:17 +0x49
F/libc    ( 7937): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8089 (hoenix.im.debug), pid 7937 (hoenix.im.debug)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-11-14 14:19:32+0300
pid: 7937, tid: 8089, name: hoenix.im.debug  >>> com.firephoenix.im.debug <<<
uid: 10156
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    eax 00000000  ebx 00001f01  ecx 00001f99  edx 00000006
    edi a9a11d29  esi 00000008
    ebp a9f645ef  esp 78c24e20  eip a93c3020
backtrace:
      #00 pc 001a7020  /data/app/~~LvuEw4leBnMhBfIYfY8hZA==/com.firephoenix.im.debug-tsjIxRdG6zafyROd6NQ4Xw==/lib/x86/libgojni.so
Lost connection to device.
Exited (sigterm)

**Comment by IDONTSUDO** [comment]
operation system ubuntu 21.04 

env: android studio emulator

**Comment by hrxiang** [comment]
After the login callback is completed
