### ISSUE TITLE
which version of flutter

### ISSUE THREAD

**Issue by ilovejs** [OpenIMSDK/Open-IM-SDK-Flutter#51]
which version of flutter are you using ?
as we have dev / stable channel...
things won't work if u define flutter >= 1.2.0

**Comment by ilovejs** [comment]
➜ flutter upgrade 
Flutter is already up to date on channel stable
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

**Comment by hrxiang** [comment]
The plugin currently supports the latest flutter 2.5.3
