### ISSUE TITLE
调用获取会话列表时报错

### ISSUE THREAD

**Issue by mofangwan23** [OpenIMSDK/Open-IM-SDK-Flutter#56]
调用方式：
  Future<void> getAllConversationList() async {
    var result = await OpenIM.iMManager.conversationManager
        .getAllConversationList()
        .then((value) => list
          ..clear()
          ..addAll(value));
    pageState = result.isEmpty ? PageState.empty : PageState.sucess;
  }
  
报错信息：
2021-12-10 14:54:56.060 10322-10588/com.quanyi.internet_hospital_doctor E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(203, sql: database is closed, null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      ConversationLogic.getAllConversationList (package:flutter_package_im/ui/pages/conversation/conversation_logic.dart:91:18)
    <asynchronous suspension>

**Comment by hrxiang** [comment]
初始化了吗。调login方法没。
