### ISSUE TITLE
msgSendProgressListener返回值不包含Msg ID，监听无法使用

### ISSUE THREAD

**Issue by 39499740** [OpenIMSDK/Open-IM-SDK-Flutter#59]
开发过程中，发送视频或图片等大数据时，发送进度回调返回msgId为空，回调仅返回发送进度数

![image](https://user-images.githubusercontent.com/29425312/147997220-d8e346b4-d2e6-43a6-8ef8-ccf41772e798.png)
![image](https://user-images.githubusercontent.com/29425312/147997231-c26439db-5f2b-49dd-b020-fde1c1dd6b81.png)
![image](https://user-images.githubusercontent.com/29425312/147997238-40c22aad-ec75-4c2c-bbbc-4d5ee9f46bd2.png)

**Comment by 39499740** [comment]
经过官方Flutter-Demo测试，iOS端100%出现，Android正常

**Comment by hrxiang** [comment]
已修复
