### ISSUE TITLE
没有消息重发的功能 ，发送失败的会一只转圈

### ISSUE THREAD

**Issue by DavidMGT** [OpenIMSDK/Open-IM-SDK-Flutter#61]
**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Is your feature request related to a problem?**

**Describe the solution you'd like**

希望有消息重发功能实现

**Describe alternatives you've considered**

**Additional context**

**Comment by hrxiang** [comment]
可以在失败后，试试调用sendMessage再次发送，实现重发。

**Comment by DavidMGT** [comment]
但是有的可以，有的就是一直转圈，也不提示发送失败。你们这个超时机制不太行

**Comment by DavidMGT** [comment]
![1644992399706](https://user-images.githubusercontent.com/12042191/154207768-181a1a02-c107-48d1-9ce2-b0b02237479e.jpg)
如图，如果我断网文字就会一直转圈 ，

**Comment by hrxiang** [comment]
好像是5分钟内都会重试发送。
