### ISSUE TITLE
[BUG] iOS: Handle MethodName Error: MessageManager's method: [createFileMessageFromFullPath] not found

### ISSUE THREAD

**Issue by myredsocks** [OpenIMSDK/Open-IM-SDK-Flutter#62]
flutter_openim_sdk:
       git:
          url: https://github.com/OpenIMSDK/Open-IM-SDK-Flutter.git
          ref: fix-ios-simulator

**Comment by hrxiang** [comment]
嗯，的确忘了配置，新版sdk更新的时候一起修复

**Comment by hrxiang** [comment]
新sdk已修复
