### ISSUE TITLE
  Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by meichengkeji** [OpenIMSDK/Open-IM-SDK-Flutter#63]
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode build...
Xcode build done.                                            4.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/0j/vs2dth5157q6r3s5lcf9wfn00000gn/T/flutter_tools.ch9shV/flutter_ios_build_temp_diryNZ4UA/temporary_xcresult_bundle

    ld: warning: ignoring file /Users/bao-mac/Downloads/Open-IM-SDK-Flutter-main/ios/Framework/OpenIMCore.framework/OpenIMCore, missing required architecture x86_64 in file /Users/bao-mac/Downloads/Open-IM-SDK-Flutter-main/ios/Framework/OpenIMCore.framework/OpenIMCore (1 slices)
    Undefined symbols for architecture x86_64:
      "_Open_im_sdkClearC2CHistoryMessage", referenced from:
          flutter_openim_sdk.MessageManager.clearC2CHistoryMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkForceSyncMsg", referenced from:
          flutter_openim_sdk.MessageManager.forceSyncMsg(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateCardMessage", referenced from:
          flutter_openim_sdk.MessageManager.createCardMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateCustomMessage", referenced from:
          flutter_openim_sdk.MessageManager.createCustomMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateLocationMessage", referenced from:
          flutter_openim_sdk.MessageManager.createLocationMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateMergerMessage", referenced from:
          flutter_openim_sdk.MessageManager.createMergerMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateFileMessageFromFullPath", referenced from:
          flutter_openim_sdk.MessageManager.createFileMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateVideoMessageFromFullPath", referenced from:
          flutter_openim_sdk.MessageManager.createVideoMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateVideoMessage", referenced from:
          flutter_openim_sdk.MessageManager.createVideoMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateImageMessageFromFullPath", referenced from:
          flutter_openim_sdk.MessageManager.createImageMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateSoundMessageFromFullPath", referenced from:
          flutter_openim_sdk.MessageManager.createSoundMessageFromFullPath(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateImageMessage", referenced from:
          flutter_openim_sdk.MessageManager.createImageMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateTextAtMessage", referenced from:
          flutter_openim_sdk.MessageManager.createTextAtMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkMarkC2CMessageAsRead", referenced from:
          flutter_openim_sdk.MessageManager.markC2CMessageAsRead(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkTypingStatusUpdate", referenced from:
          flutter_openim_sdk.MessageManager.typingStatusUpdate(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkInsertSingleMessageToLocalStorage", referenced from:
          flutter_openim_sdk.MessageManager.insertSingleMessageToLocalStorage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkFindMessages", referenced from:
          flutter_openim_sdk.MessageManager.findMessages(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkGetHistoryMessageList", referenced from:
          flutter_openim_sdk.MessageManager.getHistoryMessageList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkDeleteMessageFromLocalStorage", referenced from:
          flutter_openim_sdk.MessageManager.deleteMessageFromLocalStorage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkAddAdvancedMsgListener", referenced from:
          flutter_openim_sdk.MessageManager.addAdvancedMsgListener(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkSendMessage", referenced from:
          flutter_openim_sdk.MessageManager.sendMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkForceSyncLoginUerInfo", referenced from:
          flutter_openim_sdk.IMMananger.forceSyncLoginUerInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkGetUsersInfo", referenced from:
          flutter_openim_sdk.IMMananger.getUsersInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkCreateSoundMessage", referenced from:
          flutter_openim_sdk.MessageManager.createSoundMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkGetOneConversation", referenced from:
          flutter_openim_sdk.ConversationManager.getOneConversation(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkAcceptGroupApplication", referenced from:
          flutter_openim_sdk.GroupManager.acceptGroupApplication(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkCreateForwardMessage", referenced from:
          flutter_openim_sdk.MessageManager.createForwardMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkCreateTextMessage", referenced from:
          flutter_openim_sdk.MessageManager.createTextMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkGetMultipleConversation", referenced from:
          flutter_openim_sdk.ConversationManager.getMultipleConversation(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkTransferGroupOwner", referenced from:
          flutter_openim_sdk.GroupManager.transferGroupOwner(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkCreateFileMessage", referenced from:
          flutter_openim_sdk.MessageManager.createFileMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkQuitGroup", referenced from:
          flutter_openim_sdk.GroupManager.quitGroup(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkGetLoginStatus", referenced from:
          flutter_openim_sdk.IMMananger.getLoginStatus(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkCreateGroup", referenced from:
          flutter_openim_sdk.GroupManager.createGroup(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkGetFriendApplicationList", referenced from:
          flutter_openim_sdk.FriendshipManager.getFriendApplicationList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkLogout", referenced from:
          flutter_openim_sdk.IMMananger.logout(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkGetAllConversationList", referenced from:
          flutter_openim_sdk.ConversationManager.getAllConversationList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkGetGroupsInfo", referenced from:
          flutter_openim_sdk.GroupManager.getGroupsInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkGetGroupMemberList", referenced from:
          flutter_openim_sdk.GroupManager.getGroupMemberList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkGetGroupMembersInfo", referenced from:
          flutter_openim_sdk.GroupManager.getGroupMembersInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkSetSdkLog", referenced from:
          flutter_openim_sdk.IMMananger.setSdkLog(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkGetGroupApplicationList", referenced from:
          flutter_openim_sdk.GroupManager.getGroupApplicationList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkKickGroupMember", referenced from:
          flutter_openim_sdk.GroupManager.kickGroupMember(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkLogin", referenced from:
          flutter_openim_sdk.IMMananger.login(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkSetGroupInfo", referenced from:
          flutter_openim_sdk.GroupManager.setGroupInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkRefuseFriendApplication", referenced from:
          flutter_openim_sdk.FriendshipManager.refuseFriendApplication(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkJoinGroup", referenced from:
          flutter_openim_sdk.GroupManager.joinGroup(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkDeleteFromFriendList", referenced from:
          flutter_openim_sdk.FriendshipManager.deleteFromFriendList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkSetFriendListener", referenced from:
          flutter_openim_sdk.FriendshipManager.setFriendListener(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkCheckFriend", referenced from:
          flutter_openim_sdk.FriendshipManager.checkFriend(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkSetSelfInfo", referenced from:
          flutter_openim_sdk.IMMananger.setSelfInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkInitSDK", referenced from:
          flutter_openim_sdk.IMMananger.initSDK(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in IMManager.o
      "_Open_im_sdkGetJoinedGroupList", referenced from:
          flutter_openim_sdk.GroupManager.getJoinedGroupList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkGetConversationListSplit", referenced from:
          flutter_openim_sdk.ConversationManager.getConversationListSplit(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkDeleteConversation", referenced from:
          flutter_openim_sdk.ConversationManager.deleteConversation(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkGetBlackList", referenced from:
          flutter_openim_sdk.FriendshipManager.getBlackList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkAcceptFriendApplication", referenced from:
          flutter_openim_sdk.FriendshipManager.acceptFriendApplication(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkPinConversation", referenced from:
          flutter_openim_sdk.ConversationManager.pinConversation(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkInviteUserToGroup", referenced from:
          flutter_openim_sdk.GroupManager.inviteUserToGroup(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkClearGroupHistoryMessage", referenced from:
          flutter_openim_sdk.MessageManager.clearGroupHistoryMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkGetFriendsInfo", referenced from:
          flutter_openim_sdk.FriendshipManager.getFriendsInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkGetConversationIDBySessionType", referenced from:
          flutter_openim_sdk.ConversationManager.getConversationIDBySessionType(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkGetConversationRecvMessageOpt", referenced from:
          flutter_openim_sdk.ConversationManager.getConversationRecvMessageOpt(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkSetConversationDraft", referenced from:
          flutter_openim_sdk.ConversationManager.setConversationDraft(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkMarkGroupMessageHasRead", referenced from:
          flutter_openim_sdk.ConversationManager.markGroupMessageHasRead(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkAddFriend", referenced from:
          flutter_openim_sdk.FriendshipManager.addFriend(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkRevokeMessage", referenced from:
          flutter_openim_sdk.MessageManager.revokeMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkDeleteFromBlackList", referenced from:
          flutter_openim_sdk.FriendshipManager.deleteFromBlackList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkRefuseGroupApplication", referenced from:
          flutter_openim_sdk.GroupManager.refuseGroupApplication(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkAddToBlackList", referenced from:
          flutter_openim_sdk.FriendshipManager.addToBlackList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkSetConversationRecvMessageOpt", referenced from:
          flutter_openim_sdk.ConversationManager.setConversationRecvMessageOpt(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkGetFriendList", referenced from:
          flutter_openim_sdk.FriendshipManager.getFriendList(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkCreateQuoteMessage", referenced from:
          flutter_openim_sdk.MessageManager.createQuoteMessage(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in MessageManager.o
      "_Open_im_sdkSetFriendInfo", referenced from:
          flutter_openim_sdk.FriendshipManager.setFriendInfo(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in FriendshipManager.o
      "_Open_im_sdkGetTotalUnreadMsgCount", referenced from:
          flutter_openim_sdk.ConversationManager.getTotalUnreadMsgCount(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkSetGroupListener", referenced from:
          flutter_openim_sdk.GroupManager.setGroupListener(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in GroupManager.o
      "_Open_im_sdkMarkSingleMessageHasRead", referenced from:
          flutter_openim_sdk.ConversationManager.markSingleMessageHasRead(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
      "_Open_im_sdkSetConversationListener", referenced from:
          flutter_openim_sdk.ConversationManager.setConversationListener(methodCall: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in ConversationManager.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

    Result bundle written to path:
    	/var/folders/0j/vs2dth5157q6r3s5lcf9wfn00000gn/T/flutter_tools.ch9shV/flutter_ios_build_temp_diryNZ4UA/temporary_xcresult_bundle

Error (Xcode): Undefined symbol: _Open_im_sdkClearC2CHistoryMessage

Error (Xcode): Undefined symbol: _Open_im_sdkForceSyncMsg

Error (Xcode): Undefined symbol: _Open_im_sdkCreateCardMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateCustomMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateLocationMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateMergerMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateFileMessageFromFullPath

Error (Xcode): Undefined symbol: _Open_im_sdkCreateVideoMessageFromFullPath

Error (Xcode): Undefined symbol: _Open_im_sdkCreateVideoMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateImageMessageFromFullPath

Error (Xcode): Undefined symbol: _Open_im_sdkCreateSoundMessageFromFullPath

Error (Xcode): Undefined symbol: _Open_im_sdkCreateImageMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateTextAtMessage

Error (Xcode): Undefined symbol: _Open_im_sdkMarkC2CMessageAsRead

Error (Xcode): Undefined symbol: _Open_im_sdkTypingStatusUpdate

Error (Xcode): Undefined symbol: _Open_im_sdkInsertSingleMessageToLocalStorage

Error (Xcode): Undefined symbol: _Open_im_sdkFindMessages

Error (Xcode): Undefined symbol: _Open_im_sdkGetHistoryMessageList

Error (Xcode): Undefined symbol: _Open_im_sdkDeleteMessageFromLocalStorage

Error (Xcode): Undefined symbol: _Open_im_sdkAddAdvancedMsgListener

Error (Xcode): Undefined symbol: _Open_im_sdkSendMessage

Error (Xcode): Undefined symbol: _Open_im_sdkForceSyncLoginUerInfo

Error (Xcode): Undefined symbol: _Open_im_sdkGetUsersInfo

Error (Xcode): Undefined symbol: _Open_im_sdkCreateSoundMessage

Error (Xcode): Undefined symbol: _Open_im_sdkGetOneConversation

Error (Xcode): Undefined symbol: _Open_im_sdkAcceptGroupApplication

Error (Xcode): Undefined symbol: _Open_im_sdkCreateForwardMessage

Error (Xcode): Undefined symbol: _Open_im_sdkCreateTextMessage

Error (Xcode): Undefined symbol: _Open_im_sdkGetMultipleConversation

Error (Xcode): Undefined symbol: _Open_im_sdkTransferGroupOwner

Error (Xcode): Undefined symbol: _Open_im_sdkCreateFileMessage

Error (Xcode): Undefined symbol: _Open_im_sdkQuitGroup

Error (Xcode): Undefined symbol: _Open_im_sdkGetLoginStatus

Error (Xcode): Undefined symbol: _Open_im_sdkCreateGroup

Error (Xcode): Undefined symbol: _Open_im_sdkGetFriendApplicationList

Error (Xcode): Undefined symbol: _Open_im_sdkLogout

Error (Xcode): Undefined symbol: _Open_im_sdkGetAllConversationList

Error (Xcode): Undefined symbol: _Open_im_sdkGetGroupsInfo

Error (Xcode): Undefined symbol: _Open_im_sdkGetGroupMemberList

Error (Xcode): Undefined symbol: _Open_im_sdkGetGroupMembersInfo

Error (Xcode): Undefined symbol: _Open_im_sdkSetSdkLog

Error (Xcode): Undefined symbol: _Open_im_sdkGetGroupApplicationList

Error (Xcode): Undefined symbol: _Open_im_sdkKickGroupMember

Error (Xcode): Undefined symbol: _Open_im_sdkLogin

Error (Xcode): Undefined symbol: _Open_im_sdkSetGroupInfo

Error (Xcode): Undefined symbol: _Open_im_sdkRefuseFriendApplication

Error (Xcode): Undefined symbol: _Open_im_sdkJoinGroup

Error (Xcode): Undefined symbol: _Open_im_sdkDeleteFromFriendList

Error (Xcode): Undefined symbol: _Open_im_sdkSetFriendListener

Error (Xcode): Undefined symbol: _Open_im_sdkCheckFriend

Error (Xcode): Undefined symbol: _Open_im_sdkSetSelfInfo

Error (Xcode): Undefined symbol: _Open_im_sdkInitSDK

Error (Xcode): Undefined symbol: _Open_im_sdkGetJoinedGroupList

Error (Xcode): Undefined symbol: _Open_im_sdkGetConversationListSplit

Error (Xcode): Undefined symbol: _Open_im_sdkDeleteConversation

Error (Xcode): Undefined symbol: _Open_im_sdkGetBlackList

Error (Xcode): Undefined symbol: _Open_im_sdkAcceptFriendApplication

Error (Xcode): Undefined symbol: _Open_im_sdkPinConversation

Error (Xcode): Undefined symbol: _Open_im_sdkInviteUserToGroup

Error (Xcode): Undefined symbol: _Open_im_sdkClearGroupHistoryMessage

Error (Xcode): Undefined symbol: _Open_im_sdkGetFriendsInfo

Error (Xcode): Undefined symbol: _Open_im_sdkGetConversationIDBySessionType

Error (Xcode): Undefined symbol: _Open_im_sdkGetConversationRecvMessageOpt

Error (Xcode): Undefined symbol: _Open_im_sdkSetConversationDraft

Error (Xcode): Undefined symbol: _Open_im_sdkMarkGroupMessageHasRead

Error (Xcode): Undefined symbol: _Open_im_sdkAddFriend

Error (Xcode): Undefined symbol: _Open_im_sdkRevokeMessage

Error (Xcode): Undefined symbol: _Open_im_sdkDeleteFromBlackList

Error (Xcode): Undefined symbol: _Open_im_sdkRefuseGroupApplication

Error (Xcode): Undefined symbol: _Open_im_sdkAddToBlackList

Error (Xcode): Undefined symbol: _Open_im_sdkSetConversationRecvMessageOpt

Error (Xcode): Undefined symbol: _Open_im_sdkGetFriendList

Error (Xcode): Undefined symbol: _Open_im_sdkCreateQuoteMessage

Error (Xcode): Undefined symbol: _Open_im_sdkSetFriendInfo

Error (Xcode): Undefined symbol: _Open_im_sdkGetTotalUnreadMsgCount

Error (Xcode): Undefined symbol: _Open_im_sdkSetGroupListener

Error (Xcode): Undefined symbol: _Open_im_sdkMarkSingleMessageHasRead

Error (Xcode): Undefined symbol: _Open_im_sdkSetConversationListener

Could not build the application for the simulator.
Error launching application on iPhone X.

**Comment by hrxiang** [comment]
你sdk的引用方式是哪一种
