### ISSUE TITLE
 断网之后重新联网消息不会自动重发，一只转圈

### ISSUE THREAD

**Issue by DavidMGT** [OpenIMSDK/Open-IM-SDK-Flutter#64]
**Describe the bug**

 如题
**How to reproduce**

4. Error occurred.

**Expected behavior**

**Screenshots (If contains)**

**Version information**
- Device: *e.g. iPhone X*
- OS: *e.g. iOS 14.7.1*
- Package Version: *e.g. v1.0.9*
- Flutter Version: *e.g. v2.8.0*

**Additional context**

**Comment by hrxiang** [comment]
新sdk已修复
