### ISSUE TITLE
[BUG] ios 无法运行

### ISSUE THREAD

**Issue by Jovines** [OpenIMSDK/Open-IM-SDK-Flutter#65]
无论是创建新项目还是在原有项目上添加这个包，ios构建都会报错，android正常
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/44845663/154835289-3b207953-f523-4254-943c-f9aa77fe7684.png">

电脑：macbook 14 m1 pro

**Comment by Jovines** [comment]
这是详细报错

Failed to build iOS app
Error output from Xcode build:
↳
    objc[24926]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1f772f678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107bf02c8). One of the two will be used. Which one is undefined.
    objc[24926]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1f772f6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107bf0318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/w2/y6zqrp2n2gd6nmrvxyq06hn80000gn/T/flutter_tools.9kXqNN/flutter_ios_build_temp_dirlsclRV/temporary_xcresult_bundle

    ld: warning: ignoring file /Users/jovines/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-1.1.1/ios/Framework/OpenIMCore.framework/OpenIMCore, missing required architecture x86_64 in file /Users/jovines/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_sdk-1.1.1/ios/Framework/OpenIMCore.framework/OpenIMCore (1 slices)

**Comment by hrxiang** [comment]
模拟器的依赖方式不一样，请在demo的issue查看解决办法
