### ISSUE TITLE
[BUG] 服务端没升级到 2.0 ，客户端升级到了 2.0 , 闪退

### ISSUE THREAD

**Issue by adger-me** [OpenIMSDK/Open-IM-SDK-Flutter#66]
![WX20220227-112604](https://user-images.githubusercontent.com/16331459/155866930-67ccf152-6b9c-4c68-8c10-143033be53ee.png)

**Comment by hrxiang** [comment]
以前的老数据清除了吗

**Comment by adger-me** [comment]
> 以前的老数据清除了吗

服务端没有清，客户端是卸载了的，我是想测服务端错误情况下的app端会不会炸
