### ISSUE TITLE
[Android] Could not find io.openim:client-sdk:1.4.5.

### ISSUE THREAD

**Issue by myredsocks** [OpenIMSDK/Open-IM-SDK-Flutter#68]
> flutter build apk

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.openim:client-sdk:1.4.5.
     Searched in the following locations:
       - [https://dl.google.com/dl/android/maven2/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [https://jcenter.bintray.com/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [https://storage.googleapis.com/download.flutter.io/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [https://repo.maven.apache.org/maven2/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [http://121.37.25.71:8081/repository/maven-releases/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [https://jitpack.io/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
       - [https://www.jitpack.io/io/openim/client-sdk/1.4.5/client-sdk-1.4.5.pom]()
     Required by:
         project :app > project :flutter_openim_sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1

**Version information**
- Device: *Android*
- Package Version: *v1.1.1*
- Flutter Version: *v2.10.3*

**Additional context**
macOS M1 Pro

**Comment by hrxiang** [comment]
你没更新到2.0.0版本吗，老版本不维护了。
