### ISSUE TITLE
我在修改群组昵称的时候，app崩溃

### ISSUE THREAD

**Issue by hackerjmss** [OpenIMSDK/Open-IM-SDK-Flutter#70]
我是采用flutter sdk 自己写UI的方式，
E/GoLog   ( 2399): 2022-03-23 08:26:18.364 [INFO] [PID:2399] [FilePath:group.go:596] [OperationID:1648023978213] [getJoinedGroupListFromSvr [groupID:"734f88856a0fed9f1b361236cc6fdd08" groupName:"\347\276\216\351\242\234" notification:"\346\265\213\350\257\225\344\270\200\344\270\213\345\271\262\345\206\234\346\264\273" introduction:"\346\224\271\345\212\250\344\270\200\344\270\213" faceURL:"http://192.168.0.110/upload/userLogo/20220323/257aa4d98b918a98a3007f8f1071fd5c.jpg" ownerUserID:"15327707919" createTime:1647956464 memberCount:3 creatorUserID:"15327707919" ] 15327707919]
E/GoLog   ( 2399): 2022-03-23 08:26:18.365 [INFO] [PID:2399] [FilePath:group.go:608] [OperationID:1648023978213] [ onLocal  [0x4000698bb0] 15327707919]
E/GoLog   ( 2399): 2022-03-23 08:26:18.365 [INFO] [PID:2399] [FilePath:group.go:610] [OperationID:1648023978213] [diff  [] [] [0] [0] 15327707919]
E/Go      ( 2399): panic: runtime error: invalid memory address or nil pointer dereference
E/Go      ( 2399): [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7883ec5788]
E/Go      ( 2399):
E/Go      ( 2399): goroutine 133 [running]:
E/Go      ( 2399): open_im_sdk/internal/group.(*Group).SyncJoinedGroupList(0x40001e2540, 0x40000d4330, 0xd)
E/Go      ( 2399): 	C:/Users/Admin/go/src/open_im_sdk/internal/group/group.go:629 +0xb68
E/Go      ( 2399): open_im_sdk/internal/group.(*Group).setGroupInfo(0x40001e2540, 0x7884301b20, 0x40000d4320, 0x40003dc7a8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
E/Go      ( 2399): 	C:/Users/Admin/go/src/open_im_sdk/internal/group/group.go:336 +0x1bc
E/Go      ( 2399): open_im_sdk/internal/group.(*Group).SetGroupInfo.func1(0x40000d4330, 0xd, 0x78847105ac, 0xc, 0x400007c0c0, 0x57, 0x400010e320, 0x20, 0x7884301b20, 0x40000d4320, ...)
E/Go      ( 2399): 	C:/Users/Admin/go/src/open_im_sdk/internal/group/open_im_sdk_group.go:100 +0x1d4
E/Go      ( 2399): created by open_im_sdk/internal/group.(*Group).SetGroupInfo
E/Go      ( 2399): 	C:/Users/Admin/go/src/open_im_sdk/internal/group/open_im_sdk_group.go:96 +0x90
F/libc    ( 2399): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 2588 (ample.flutterim), pid 2399 (ample.flutterim)
Softversion: PD1806_A_9.8.11
Time: 2022-03-23 16:26:18
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'vivo/PD1806/PD1806:10/QP1A.190711.020/compiler12292219:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-03-23 16:26:18+0800
pid: 2399, tid: 2588, name: ample.flutterim  >>> com.example.flutterim <<<
uid: 10200
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0  0000000000000000  x1  0000000000000a1c  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000001  x5  000000788401dbab  x6  000000000000003f  x7  0000000000000030
    x8  0000000000000083  x9  0000000000000050  x10 00000000623ad9aa  x11 0000000016d5fce7
    x12 0000000000000018  x13 00000000623ad9aa  x14 0016a94b0cd6e151  x15 00002cb1da950c1b
    x16 00000078839160d3  x17 00000078839160d0  x18 0000007840d8a000  x19 000000000000095f
    x20 0000007904f72760  x21 0000004000090c00  x22 0000000000000001  x23 0000007904f72dd8
    x24 0000007904f72d50  x25 0000007904f72d50  x26 0000000000000000  x27 0000000000000010
    x28 00000040004fca80  x29 0000000000000000
    sp  000000400072d570  lr  00000078838fac80  pc  0000007883916e38
backtrace:
      #00 pc 000000000044ee38  /data/app/com.example.flutterim-ABiQeP456dfiCrlxi15MGg==/lib/arm64/libgojni.so
Lost connection to device.

**Comment by hrxiang** [comment]
你这传入的是啥：groupName:"\347\276\216\351\242\234" notification:"\346\265\213\350\257\225\344\270\200\344\270\213\345\271\262\345\206\234\346\264\273" introduction:"\346\224\271\345\212\250\344\270\200\344\270\213"
