### ISSUE TITLE
[BUG] android 运行报错

### ISSUE THREAD

**Issue by weishirongzhen** [OpenIMSDK/Open-IM-SDK-Flutter#72]
重现步骤：clone后，flutter pub get, 然后运行

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.1-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.1)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by hrxiang** [comment]
，，sdk里并没有引用其他第三方的插件，如果是demo问题请到demo仓库提issue
