### ISSUE TITLE
[BUG] 极光无法对安卓进行离线推送

### ISSUE THREAD

**Issue by hackerjmss** [OpenIMSDK/Open-IM-SDK-Flutter#73]
**Describe the bug**
服务端已经配置好了极光的推送设置，在发送消息的时候，也对offlinePushInfo字段进行了配置，但是在极光的推送后台查看到 是推送的IOS的类别的，但是我是安卓，不知道这个是在哪里进行更改为安卓字段的，另外 我发送的消息，以及登陆的都是安卓 也是正确配置

**Comment by suyie001** [comment]
请问是怎么解决的
