### ISSUE TITLE
[BUG] 登录成功后退到后台,等待链接超时后进入app,再退出,这个时候会出现一直反复连接中

### ISSUE THREAD

**Issue by sbiweeq** [OpenIMSDK/Open-IM-SDK-Flutter#76]
登录成功后退到后台,等待链接超时后进入app,再退出,这个时候会出现一直反复连接中

**Screenshots (If contains)**
![image](https://user-images.githubusercontent.com/10651998/162653414-63098132-181f-45b9-8461-7a4ea0e4a048.png)

**Comment by adger-me** [comment]
我也有这个问题

![image](https://user-images.githubusercontent.com/16331459/162777597-1c9e6e15-ef18-41fb-9abf-cf212f90127f.png)
