### ISSUE TITLE
[BUG] 删除会话后,再次发送新消息,重新拉取会话列表接口,这个时候接口数据为空

### ISSUE THREAD

**Issue by sbiweeq** [OpenIMSDK/Open-IM-SDK-Flutter#77]
**Describe the bug**

     删除会话后,再次发送新消息,重新拉取会话列表接口,这个时候接口数据为空,
新会话监听接口有数据返回
不使用新会话监听接口返回的数据,直接重新拉取会话,这个时候永远都获取不了数据,一直是空数组
,当会话删除后,消息数监听接口,也不会再触发了

**Comment by hrxiang** [comment]
建议会话的更新通过会话改变跟新增回调实现。
