### ISSUE TITLE
[BUG] 获取用户在线离线状态，接口报500错误

### ISSUE THREAD

**Issue by bhlin790** [OpenIMSDK/Open-IM-SDK-Flutter#79]
flutter: ╔╣ DioError ║ Status: 500 Internal Server Error
flutter: ║  [http://121.37.25.71:10000/manager/get_users_online_status]()
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝
flutter: ╔ DioErrorType.response
flutter: ║    {
flutter: ║         errCode: 500,
flutter: ║         errMsg: "GetUserIDFromToken failed"
flutter: ║    }
flutter: ╚══════════════════════════════════════════════════════════════════════════════════════════╝

**Comment by tong424** [comment]
我的也是，尚未解决
