### ISSUE TITLE
[BUG] 在IOS中无法初始化

### ISSUE THREAD

**Issue by hackerjmss** [OpenIMSDK/Open-IM-SDK-Flutter#80]
我的模拟器为IOS15.4,然后同样的代码在android上面可以正常使用并运行，在进行ios测试时，无法初始化，返回null，求解

**Comment by hackerjmss** [comment]
在执行其他的方法时，提示 905 resource loading is not complete

**Comment by hrxiang** [comment]
模拟器 你要使用模拟器分支。

**Comment by std-s** [comment]
> 我的模拟器为IOS15.4,然后同样的代码在android上面可以正常使用并运行，在进行ios测试时，无法初始化，返回null，求解

更新sdk。
