### ISSUE TITLE
多次重启APP后用原有的token登录im，大概率出现 PlatformException(301, operationID[1651076796426], info[recv timeout, conn same], null, null)

### ISSUE THREAD

**Issue by adger-me** [OpenIMSDK/Open-IM-SDK-Flutter#81]
![image](https://user-images.githubusercontent.com/16331459/165567449-be24306b-9c80-4623-92d1-c828d09b3528.png)

**Comment by suyie001** [comment]
> ![image](https://user-images.githubusercontent.com/16331459/165567449-be24306b-9c80-4623-92d1-c828d09b3528.png)

这位兄弟怎么解决的

**Comment by zhanglijie5997** [comment]
> > ![image](https://user-images.githubusercontent.com/16331459/165567449-be24306b-9c80-4623-92d1-c828d09b3528.png)
> 
> 这位兄弟怎么解决的

怎么解决的？

**Comment by pppshiwen** [comment]
兄弟怎么解决的
