### ISSUE TITLE
[Flutter-Android] 生成的libgojni.so太大

### ISSUE THREAD

**Issue by DizzyDuan** [OpenIMSDK/Open-IM-SDK-Flutter#82]
生成的libgojni.so太大

已经达到15M

**Comment by hrxiang** [comment]
支持的cpu架构你可以只配置一种

**Comment by DizzyYang** [comment]
只配置了
armeabi-v7a

libgojni.so达到15.4M

**Comment by hrxiang** [comment]
> 只配置了 armeabi-v7a
> 
> libgojni.so达到15.4M

go sdk生成的 aar包就有24m，现在手机内存那么大，不在乎这点。
