### ISSUE TITLE
resource loading is not complete

### ISSUE THREAD

**Issue by Stitch-Taotao** [OpenIMSDK/Open-IM-SDK-Flutter#85]
## error:  resource loading is not complete 

这个bug 有时候出现，有时候不出现，我是在connecting sucess之后调用 请求联系人列表出现的（**按理说这时methodChannel应该已经初始化成功了**）
即 这个方法的出的问题：
```
OpenIM.iMManager.conversationManager
        .getConversationListSplit
```
![image](https://user-images.githubusercontent.com/26296915/167985418-eb28916c-e177-4a7a-8103-ffd23b07c2d8.png)
![image](https://user-images.githubusercontent.com/26296915/167985470-9598888a-01c5-44d4-beb3-72aac0aa458f.png)

**Comment by hrxiang** [comment]
1，保证监听器都设置完成后调的login方法
2，保证login方法回调结束后做的其他查询

**Comment by std-s** [comment]
@Stitch-Taotao  login success 以后再调用其它API。
