### ISSUE TITLE
[BUG] 最新版本build失败

### ISSUE THREAD

**Issue by fuyuku** [OpenIMSDK/Open-IM-SDK-Flutter#86]
**Describe the bug**

* What went wrong:
A problem occurred configuring project ':flutter_openim_sdk'.
> Could not resolve all dependencies for configuration ':flutter_openim_sdk:classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven3(http://maven.aliyun.com/nexus/content/groups/public)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_openim_sdk' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_openim_sdk' of type org.gradle.api.Project.

所有环境都是最新版本
flutter_openim_sdk: ^2.0.8 
flutter:3.0 
gradle:7.4.2 
com.android.tools.build:gradle:7.1.3

**Comment by hrxiang** [comment]
降低gradle版本试试

**Comment by fuyuku** [comment]
低版本是好的  但是最新flutter默认7.4 还是需要解决一下的

**Comment by fuyuku** [comment]
好的
