### ISSUE TITLE
缺少添加或者删除管理员功能，只能在创建群的时候添加管理员

### ISSUE THREAD

**Issue by YUZML** [OpenIMSDK/Open-IM-SDK-Flutter#87]
///
/// @param groupName 群名
/// @param notification 群公告
/// @param introduction 群简介
/// @param faceUrl 群icon
/// @param list（List<GroupMemberRole>）    被选择的群成员
/// @return Future 
OpenIM.iMManager.groupManager.createGroup(
    groupName: groupName,
    notification: notification,
    introduction: introduction,
    faceUrl: faceUrl,
  list: list,)
只有这个创建群的接口能够设置管理员，

**Comment by hrxiang** [comment]
已经在调试了，请留意下个版本

**Comment by hrxiang** [comment]
方法已经有了
