### ISSUE TITLE
获取储存于服务器上的历史消息

### ISSUE THREAD

**Issue by cg-flsunshine** [OpenIMSDK/Open-IM-SDK-Flutter#88]
我发现在sdk里边只有一个方法用来获取历史聊天记录，并且没有标明是从服务器获取的还是本地获取的。同时我发现删除消息时api有标明是删除服务器的还是本地的，所以我想问下，这个api ”OpenIM.iMManager.messageManager.getHistoryMessageList“ 是从哪里获取的消息记录？

**Comment by hrxiang** [comment]
每次启动会先同步服务器的消息到本地，这个方法是获取的本地消息但来自服务器。
