### ISSUE TITLE
OpenIMCore2.0.9: Cannot find 'Open_im_sdkSetGroupMemberRoleLevel'

### ISSUE THREAD

**Issue by GarrettLi77** [OpenIMSDK/Open-IM-SDK-Flutter#89]
在OpenIMCore2.0.9的版本中，找不到Open_im_sdkSetGroupMemberRoleLevel这个方法。

使用OpenIMCore2.1.0之后
[!] CocoaPods could not find compatible versions for pod "OpenIMSDKCore":
  In Podfile:
    flutter_openim_sdk (from `.symlinks/plugins/flutter_openim_sdk/ios`) was resolved to 0.0.1, which depends on
      OpenIMSDKCore (= 2.1.0)

None of your spec sources contain a spec satisfying the dependency: `OpenIMSDKCore (= 2.1.0)`.

**Comment by hrxiang** [comment]
更新最新sdk
