### ISSUE TITLE
[BUG] 升级版本2.3.0后 OpenIM.iMManager.conversationManager.markGroupMessageHasRead(groupID: id) 方法报错

### ISSUE THREAD

**Issue by zhuhean** [OpenIMSDK/Open-IM-SDK-Flutter#92]
**Describe the bug**
升级版本2.3.0后调用 OpenIM.iMManager.conversationManager.markGroupMessageHasRead(groupID: id) 方法报错
报错详情：
I/F-OpenIMSDK(flutter call native)(32731): method: 【 markGroupMessageHasRead 】, onError: { code:802, message:operationID[1660530807269], info[==> open_im_sdk/pkg/db.(*DataBase).GetConversation()@93: GetConversation failed: record not found]}
E/flutter (32731): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(802, operationID[1660530807269], info[==> open_im_sdk/pkg/db.(*DataBase).GetConversation()@93: GetConversation failed: record not found], null, null)

**How to reproduce**
1. 正常初始化 OpenIM
2. 正常登录 OpenIM
3. 调用 OpenIM.iMManager.conversationManager.markGroupMessageHasRead(groupID: id)

**Expected behavior**
预期调用 OpenIM.iMManager.conversationManager.markGroupMessageHasRead(groupID: id) 功能正常

**Version information**
- Device: Samsung Galaxy S8
- OS: Android 9
- Package Version: 2.3.0
- Flutter Version: Channel beta, 3.3.0-0.1.pre

**Comment by std-s** [comment]
> markGroupMessageHasRead

@zhuhean 

群聊：OpenIM.iMManager.messageManager.markGroupMessageAsRead() 
单聊：OpenIM.iMManager.messageManager.markC2CMessageAsRead()

推荐：OpenIM.iMManager.messageManager.markMessageAsReadByConID()
