### ISSUE TITLE
[BUG] signalingInviteInGroup' 无法发送消息

### ISSUE THREAD

**Issue by simanlx** [OpenIMSDK/Open-IM-SDK-Flutter#96]
/// 邀请群里某些人加入音视频
  /// [info] 信令对象[SignalingInfo]
  Future<SignalingCertificate> signalingInviteInGroup({
    required SignalingInfo info,
    String? operationID,
  })
  {
    print("sdk2======================");
    print(info.toJson());
    return _channel
      .invokeMethod(
  'signalingInviteInGroup',
  _buildParam({
  'signalingInfo': info.toJson(),
  'operationID': Utils.checkOperationID(operationID),
  }))
      .then((value) =>
      Utils.toObj(value, (map) => SignalingCertificate.fromJson(map)));
}

signalingInvite  可以发送   signalingInviteInGroup不可以

**Comment by hrxiang** [comment]
通过onReceiveNewInvitation回调
