### ISSUE TITLE
升级到 2.3.4+2 后swift编译失败

### ISSUE THREAD

**Issue by liujian-930212** [OpenIMSDK/Open-IM-SDK-Flutter#98]
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/84756838/198520945-0c3b82a9-8f6f-4bc0-b209-dccac689fd60.png">
如图 
项目中我搜索函数的定义 并没搜到 只搜到了调用
![image](https://user-images.githubusercontent.com/84756838/198521095-176dcbd6-7443-4fc7-aaa9-7ebb25ea0d91.png)
请问这是怎么回事

**Comment by hrxiang** [comment]
更新最新sdk ，重新pod
