### ISSUE TITLE
minio如何上传到指定的目录，并且修改文件名？

### ISSUE THREAD

**Issue by bugAlwaysExists** [OpenIMSDK/Open-IM-SDK-Flutter#99]
目前默认都是在根目录，并且默认生成 d%-d% 的文件名， 名字太长了

**Comment by BaiMoHan** [comment]
需要修改Open-IM-sdk-core包里面的代码，具体修改sdk-core/internal/obj_storage/minio.go#getNewFileNameAndContentType，里面有文件名生成策略。修改完成后再编译一遍构成Flutter依赖即可

**Comment by BaiMoHan** [comment]
> 目前默认都是在根目录，并且默认生成 d%-d% 的文件名， 名字太长了

见上文
